name: Pull request

on:
  pull_request:

jobs:
  build:
    name: Build
    if: false
    uses: ./.github/workflows/reusable-build.yml
    with:
      artifact-name: build
  test:
    name: Test
    if: false
    uses: ./.github/workflows/reusable-test.yml
  lint:
    name: Lint
    if: false
    uses: ./.github/workflows/reusable-lint.yml
  performance:
    name: Performance
    if: false
    needs: build
    uses: ./.github/workflows/reusable-performance.yml
    with:
      build-artifact-name: build
    secrets:
      LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}
  deploy-preview:
    name: Deploy preview
    # needs: [build, lint, test, performance]
    uses: ./.github/workflows/reusable-deploy-cloudflare-pages.yml
    # Quote to avoid YAML issues with "!" at the beginning
    # https://github.com/actions/runner/issues/753
    if: "! github.event.pull_request.head.repo.fork && github.event.pull_request.state == 'open'"
    with:
      build-artifact-name: build
    secrets:
      cloudflare-account-id: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
      cloudflare-api-token: ${{ secrets.CLOUDFLARE_API_TOKEN }}
    permissions:
      contents: read
      deployments: write
