name: Deploy to Cloudflare Pages

on:
  workflow_call:
    inputs:
      build-artifact-name:
        required: true
        type: string
    secrets:
      cloudflare-account-id:
        required: true
      cloudflare-api-token:
        required: true

permissions:
  contents: read
  deployments: write

concurrency:
  group: cloudflare-pages-${{ github.ref }}
  cancel-in-progress: false

jobs:
  deploy:
    name: Deploy to Cloudflare Pages
    runs-on: ubuntu-latest
    steps:
      - name: Check if reference exists
        id: ref-exists
        uses: actions/github-script@v6
        with:
          script: |
            let ref = "";
            try {
              ref = await github.rest.git.getRef({
                owner: context.repo.owner,
                repo: context.repo.repo,
                ref: "add-animations",
                //ref: `heads/${context.payload.pull_request.head.ref}`,
              })
            catch (error) {
              console.log(JSON.stringify(error))
              throw error
            }
            return ref
      - name: Echo result
        run: echo '${{ toJson(steps.ref-exists.outputs.result) }}'
#      - name: Download built app
#        uses: actions/download-artifact@v3
#        with:
#          name: ${{ inputs.build-artifact-name }}
#      - name: Publish
#        uses: cloudflare/pages-action@1
#        with:
#          accountId: ${{ secrets.cloudflare-account-id }}
#          apiToken: ${{ secrets.cloudflare-api-token }}
#          projectName: 'davidlj95-v2'
#          directory: 'browser'
#          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
